apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: plataforma-civica
type: Opaque
stringData:
  POSTGRES_DB: plataforma_civica
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgreseps