apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: plataforma-civica
type: Opaque
stringData:
  JWT_SECRET: supersecretkey
  DATABASE_URL: postgres://postgres:postgreseps@database:5432/plataforma_civica